import { db, pool, hospitalsTable } from "@workspace/db";

async function ensureHospitalsSchema() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS hospitals (
      id serial PRIMARY KEY,
      name text NOT NULL,
      image_url text NOT NULL DEFAULT '',
      description text NOT NULL DEFAULT '',
      address text NOT NULL,
      city text NOT NULL DEFAULT '',
      state text NOT NULL DEFAULT '',
      phone text NOT NULL,
      email text NOT NULL DEFAULT '',
      website text,
      specialties text[] NOT NULL DEFAULT '{}',
      total_beds integer NOT NULL DEFAULT 0,
      available_beds integer NOT NULL DEFAULT 0,
      total_icu_beds integer NOT NULL DEFAULT 0,
      available_icu_beds integer NOT NULL DEFAULT 0,
      emergency_available boolean NOT NULL DEFAULT true,
      ambulance_available boolean NOT NULL DEFAULT true,
      rating real,
      latitude real,
      longitude real,
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `);

  await pool.query(`
    DO $$ BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'hospitals' AND column_name = 'beds_available'
      ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'hospitals' AND column_name = 'available_beds'
      ) THEN
        ALTER TABLE hospitals RENAME COLUMN beds_available TO available_beds;
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'hospitals' AND column_name = 'icu_available'
      ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'hospitals' AND column_name = 'available_icu_beds'
      ) THEN
        ALTER TABLE hospitals RENAME COLUMN icu_available TO available_icu_beds;
      END IF;
    END $$
  `);

  const columns = [
    "image_url text NOT NULL DEFAULT ''",
    "description text NOT NULL DEFAULT ''",
    "city text NOT NULL DEFAULT ''",
    "state text NOT NULL DEFAULT ''",
    "email text NOT NULL DEFAULT ''",
    "website text",
    "total_beds integer NOT NULL DEFAULT 0",
    "total_icu_beds integer NOT NULL DEFAULT 0",
    "emergency_available boolean NOT NULL DEFAULT true",
    "ambulance_available boolean NOT NULL DEFAULT true",
    "latitude real",
    "longitude real",
    "created_at timestamptz NOT NULL DEFAULT now()",
  ];

  for (const col of columns) {
    await pool.query(`ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS ${col}`);
  }

  await pool.query(`ALTER TABLE hospitals DROP COLUMN IF EXISTS distance`);
}

const IMAGES = [
  "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&q=80",
  "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
  "https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?w=800&q=80",
  "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&q=80",
  "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
  "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80",
  "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=800&q=80",
  "https://images.unsplash.com/photo-1504813184591-01572f98c85f?w=800&q=80",
];

const hospitals = [
  {
    name: "Apollo Hospitals, Jubilee Hills",
    imageUrl: IMAGES[0],
    description:
      "Apollo Hospitals Jubilee Hills is a flagship multi-specialty tertiary care hospital offering world-class healthcare with advanced diagnostics, robotic surgery, and comprehensive emergency services.",
    address: "Road No. 72, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 2360 7777",
    email: "info@apollohyderabad.com",
    website: "https://www.apollohospitals.com",
    specialties: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "Emergency Medicine"],
    totalBeds: 550,
    availableBeds: 87,
    totalICUBeds: 80,
    availableICUBeds: 12,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.8,
    latitude: 17.4239,
    longitude: 78.4078,
  },
  {
    name: "Apollo Hospitals, Chennai",
    imageUrl: IMAGES[1],
    description:
      "One of India's largest healthcare groups, Apollo Chennai delivers advanced cardiac care, organ transplants, and comprehensive multi-specialty treatment.",
    address: "21 Greams Lane, Off Greams Road",
    city: "Chennai",
    state: "Tamil Nadu",
    phone: "+91 44 2829 3333",
    email: "chennai@apollohospitals.com",
    website: "https://www.apollohospitals.com",
    specialties: ["Cardiology", "Nephrology", "Gastroenterology", "Oncology", "General Surgery"],
    totalBeds: 700,
    availableBeds: 112,
    totalICUBeds: 95,
    availableICUBeds: 18,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.9,
    latitude: 13.0604,
    longitude: 80.2496,
  },
  {
    name: "Yashoda Hospitals, Secunderabad",
    imageUrl: IMAGES[2],
    description:
      "Yashoda Secunderabad is a leading NABH-accredited hospital known for cardiac sciences, neurosciences, and high-quality patient-centric care across specialties.",
    address: "Alexander Road, Secunderabad",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 4567 4567",
    email: "secunderabad@yashodahospitals.com",
    website: "https://www.yashodahospitals.com",
    specialties: ["Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Pulmonology"],
    totalBeds: 400,
    availableBeds: 64,
    totalICUBeds: 45,
    availableICUBeds: 8,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.7,
    latitude: 17.4399,
    longitude: 78.4983,
  },
  {
    name: "Yashoda Hospitals, Malakpet",
    imageUrl: IMAGES[3],
    description:
      "A trusted community hospital in Malakpet offering affordable multi-specialty care with modern ICU facilities and 24/7 emergency services.",
    address: "Nalgonda X Roads, Malakpet",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 2455 5555",
    email: "malakpet@yashodahospitals.com",
    website: "https://www.yashodahospitals.com",
    specialties: ["General Surgery", "Gynecology", "Pediatrics", "Orthopedics", "Emergency Medicine"],
    totalBeds: 250,
    availableBeds: 41,
    totalICUBeds: 25,
    availableICUBeds: 5,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.5,
    latitude: 17.3745,
    longitude: 78.5074,
  },
  {
    name: "KIMS Hospitals, Secunderabad",
    imageUrl: IMAGES[4],
    description:
      "KIMS Secunderabad is a premier NABH-accredited hospital offering advanced medical care across 30+ specialties with state-of-the-art infrastructure.",
    address: "1-112 / 86, Survey No 5, KPHB Colony",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 4488 5000",
    email: "info@kimshospitals.com",
    website: "https://www.kimshospitals.com",
    specialties: ["Cardiology", "Neurology", "Oncology", "Nephrology", "Urology"],
    totalBeds: 450,
    availableBeds: 72,
    totalICUBeds: 55,
    availableICUBeds: 9,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.6,
    latitude: 17.4435,
    longitude: 78.3772,
  },
  {
    name: "AIG Hospitals, Gachibowli",
    imageUrl: IMAGES[5],
    description:
      "AIG Hospitals is a quaternary care facility specializing in gastroenterology, liver transplants, and advanced minimally invasive procedures.",
    address: "Mindspace Road, Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 4244 4244",
    email: "info@aighospitals.com",
    website: "https://www.aighospitals.com",
    specialties: ["Gastroenterology", "Hepatology", "General Surgery", "Oncology", "Nephrology"],
    totalBeds: 350,
    availableBeds: 48,
    totalICUBeds: 40,
    availableICUBeds: 6,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.8,
    latitude: 17.4401,
    longitude: 78.3489,
  },
  {
    name: "Care Hospitals, Banjara Hills",
    imageUrl: IMAGES[6],
    description:
      "Care Hospitals Banjara Hills provides comprehensive tertiary care with expertise in cardiac sciences, neurosciences, and critical care medicine.",
    address: "Road No. 1, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 3041 8888",
    email: "banjarahills@carehospitals.com",
    website: "https://www.carehospitals.com",
    specialties: ["Cardiology", "Neurology", "Orthopedics", "Pulmonology", "Emergency Medicine"],
    totalBeds: 380,
    availableBeds: 55,
    totalICUBeds: 42,
    availableICUBeds: 7,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.6,
    latitude: 17.4156,
    longitude: 78.4347,
  },
  {
    name: "Sunshine Hospitals, Secunderabad",
    imageUrl: IMAGES[7],
    description:
      "Sunshine Hospitals is a patient-focused multi-specialty hospital offering quality healthcare with modern infrastructure and experienced specialists.",
    address: "Penderghast Road, Secunderabad",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 4455 0000",
    email: "info@sunshinehospitals.com",
    website: "https://www.sunshinehospitals.com",
    specialties: ["Orthopedics", "General Surgery", "Pediatrics", "Gynecology", "Dermatology"],
    totalBeds: 200,
    availableBeds: 38,
    totalICUBeds: 18,
    availableICUBeds: 4,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.4,
    latitude: 17.4391,
    longitude: 78.4989,
  },
  {
    name: "Continental Hospitals, Gachibowli",
    imageUrl: IMAGES[0],
    description:
      "Continental Hospitals is a JCI-accredited quaternary care facility with advanced robotic surgery, comprehensive cancer care, and transplant programs.",
    address: "Plot No. 3, Road No. 2, IT & Financial District",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 6700 0000",
    email: "info@continentalhospitals.com",
    website: "https://www.continentalhospitals.com",
    specialties: ["Oncology", "Cardiology", "Neurology", "Orthopedics", "General Surgery"],
    totalBeds: 500,
    availableBeds: 76,
    totalICUBeds: 60,
    availableICUBeds: 11,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.7,
    latitude: 17.4432,
    longitude: 78.3491,
  },
  {
    name: "Medicover Hospitals, Madhapur",
    imageUrl: IMAGES[1],
    description:
      "Medicover Madhapur offers European-standard healthcare with advanced diagnostics, maternity care, and multi-specialty outpatient and inpatient services.",
    address: "HITEC City, Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 6833 4455",
    email: "madhapur@medicoverhospitals.in",
    website: "https://www.medicoverhospitals.in",
    specialties: ["Gynecology", "Pediatrics", "Cardiology", "Orthopedics", "ENT"],
    totalBeds: 300,
    availableBeds: 52,
    totalICUBeds: 28,
    availableICUBeds: 6,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.5,
    latitude: 17.4486,
    longitude: 78.3908,
  },
  {
    name: "Nizam's Institute of Medical Sciences",
    imageUrl: IMAGES[2],
    description:
      "NIMS is a premier government super-specialty institute offering advanced neurosurgery, cardiac care, and research-driven clinical excellence.",
    address: "Punjagutta",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91 40 2348 9000",
    email: "director@nims.edu.in",
    website: "https://www.nims.edu.in",
    specialties: ["Neurology", "Cardiology", "Nephrology", "General Surgery", "Orthopedics"],
    totalBeds: 900,
    availableBeds: 45,
    totalICUBeds: 70,
    availableICUBeds: 3,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.6,
    latitude: 17.4254,
    longitude: 78.4502,
  },
  {
    name: "KIMS Hospital, Vijayawada",
    imageUrl: IMAGES[3],
    description:
      "KIMS Vijayawada serves coastal Andhra Pradesh with comprehensive multi-specialty care, advanced ICU, and round-the-clock emergency services.",
    address: "NH-16, Benz Circle",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    phone: "+91 866 666 7777",
    email: "vijayawada@kimshospitals.com",
    website: "https://www.kimshospitals.com",
    specialties: ["Cardiology", "Orthopedics", "Pediatrics", "General Surgery", "Pulmonology"],
    totalBeds: 320,
    availableBeds: 58,
    totalICUBeds: 30,
    availableICUBeds: 7,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.5,
    latitude: 16.5062,
    longitude: 80.648,
  },
  {
    name: "Fortis Hospital, Bannerghatta Road",
    imageUrl: IMAGES[4],
    description:
      "Fortis Bannerghatta is a leading multi-specialty hospital in Bangalore offering advanced cardiac care, organ transplants, and comprehensive oncology services.",
    address: "154 / 9, Bannerghatta Road",
    city: "Bangalore",
    state: "Karnataka",
    phone: "+91 80 6621 4444",
    email: "bannerghatta@fortishealthcare.com",
    website: "https://www.fortishealthcare.com",
    specialties: ["Cardiology", "Oncology", "Neurology", "Orthopedics", "Nephrology"],
    totalBeds: 480,
    availableBeds: 68,
    totalICUBeds: 50,
    availableICUBeds: 10,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.7,
    latitude: 12.8878,
    longitude: 77.597,
  },
  {
    name: "Manipal Hospital, Old Airport Road",
    imageUrl: IMAGES[5],
    description:
      "Manipal Old Airport Road is a NABH-accredited tertiary care hospital known for clinical excellence across 60+ specialties and advanced medical technology.",
    address: "98, HAL Airport Road",
    city: "Bangalore",
    state: "Karnataka",
    phone: "+91 80 2502 4444",
    email: "info@manipalhospitals.com",
    website: "https://www.manipalhospitals.com",
    specialties: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "Gastroenterology"],
    totalBeds: 600,
    availableBeds: 94,
    totalICUBeds: 65,
    availableICUBeds: 14,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.8,
    latitude: 12.9601,
    longitude: 77.6489,
  },
  {
    name: "AIIMS, New Delhi",
    imageUrl: IMAGES[6],
    description:
      "All India Institute of Medical Sciences is India's premier public medical institute offering super-specialty care, research, and medical education at the highest level.",
    address: "Ansari Nagar, Aurobindo Marg",
    city: "New Delhi",
    state: "Delhi",
    phone: "+91 11 2658 8500",
    email: "info@aiims.edu",
    website: "https://www.aiims.edu",
    specialties: ["Cardiology", "Neurology", "Oncology", "General Surgery", "Nephrology"],
    totalBeds: 2500,
    availableBeds: 120,
    totalICUBeds: 200,
    availableICUBeds: 8,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.9,
    latitude: 28.5672,
    longitude: 77.21,
  },
  {
    name: "Lilavati Hospital, Mumbai",
    imageUrl: IMAGES[7],
    description:
      "Lilavati Hospital is one of Mumbai's most trusted private hospitals, offering world-class multi-specialty care with a strong focus on patient safety.",
    address: "A-791, Bandra Reclamation, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    phone: "+91 22 2675 1000",
    email: "info@lilavatihospital.com",
    website: "https://www.lilavatihospital.com",
    specialties: ["Cardiology", "Oncology", "Neurology", "Orthopedics", "Gynecology"],
    totalBeds: 420,
    availableBeds: 59,
    totalICUBeds: 48,
    availableICUBeds: 9,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.8,
    latitude: 19.0544,
    longitude: 72.8311,
  },
  {
    name: "Kokilaben Dhirubhai Ambani Hospital",
    imageUrl: IMAGES[0],
    description:
      "KDAH is a world-class quaternary care hospital in Mumbai offering advanced robotic surgery, comprehensive cancer care, and multi-organ transplant programs.",
    address: "Rao Saheb Achutrao Patwardhan Marg, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    phone: "+91 22 3099 9999",
    email: "info@kokilabenhospital.com",
    website: "https://www.kokilabenhospital.com",
    specialties: ["Oncology", "Cardiology", "Neurology", "Orthopedics", "Pediatrics"],
    totalBeds: 750,
    availableBeds: 98,
    totalICUBeds: 85,
    availableICUBeds: 15,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.9,
    latitude: 19.1313,
    longitude: 72.8267,
  },
  {
    name: "Medanta - The Medicity",
    imageUrl: IMAGES[1],
    description:
      "Medanta Gurgaon is one of India's largest multi-super specialty institutes with dedicated centers of excellence in cardiac, neuro, and oncology care.",
    address: "Sector 38, Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    phone: "+91 124 414 1414",
    email: "info@medanta.org",
    website: "https://www.medanta.org",
    specialties: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "Nephrology"],
    totalBeds: 1250,
    availableBeds: 156,
    totalICUBeds: 120,
    availableICUBeds: 22,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.9,
    latitude: 28.4595,
    longitude: 77.0266,
  },
  {
    name: "Max Super Specialty Hospital, Saket",
    imageUrl: IMAGES[2],
    description:
      "Max Saket is a leading NABH-accredited hospital in Delhi NCR offering advanced cardiac, oncology, and transplant services with international quality standards.",
    address: "1, Press Enclave Road, Saket",
    city: "New Delhi",
    state: "Delhi",
    phone: "+91 11 4055 4055",
    email: "saket@maxhealthcare.com",
    website: "https://www.maxhealthcare.in",
    specialties: ["Cardiology", "Oncology", "Neurology", "Orthopedics", "General Surgery"],
    totalBeds: 530,
    availableBeds: 74,
    totalICUBeds: 55,
    availableICUBeds: 11,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.7,
    latitude: 28.5275,
    longitude: 77.219,
  },
  {
    name: "Christian Medical College, Vellore",
    imageUrl: IMAGES[3],
    description:
      "CMC Vellore is one of India's oldest and most respected medical institutions, renowned for clinical excellence, research, and compassionate patient care.",
    address: "IDA Scudder Road",
    city: "Vellore",
    state: "Tamil Nadu",
    phone: "+91 416 228 1000",
    email: "info@cmch-vellore.edu",
    website: "https://www.cmch-vellore.edu",
    specialties: ["General Surgery", "Cardiology", "Nephrology", "Neurology", "Oncology"],
    totalBeds: 2800,
    availableBeds: 180,
    totalICUBeds: 150,
    availableICUBeds: 12,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.8,
    latitude: 12.9249,
    longitude: 79.1353,
  },
  {
    name: "Aster Medcity, Kochi",
    imageUrl: IMAGES[4],
    description:
      "Aster Medcity is a quaternary care hospital in Kochi with dedicated centers for cardiac sciences, neurosciences, and organ transplantation.",
    address: "Kuttisahib Road, Near Kothad Bridge",
    city: "Kochi",
    state: "Kerala",
    phone: "+91 484 669 9999",
    email: "info@astermedcity.com",
    website: "https://www.astermedcity.com",
    specialties: ["Cardiology", "Neurology", "Oncology", "Nephrology", "Orthopedics"],
    totalBeds: 670,
    availableBeds: 88,
    totalICUBeds: 58,
    availableICUBeds: 10,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.7,
    latitude: 9.9987,
    longitude: 76.2999,
  },
  {
    name: "Narayana Health, Bangalore",
    imageUrl: IMAGES[5],
    description:
      "Narayana Health Bangalore is a flagship cardiac and multi-specialty hospital offering affordable, high-quality healthcare with one of India's largest cardiac programs.",
    address: "258/A, Bommasandra Industrial Area",
    city: "Bangalore",
    state: "Karnataka",
    phone: "+91 80 7122 2222",
    email: "info@narayanahealth.org",
    website: "https://www.narayanahealth.org",
    specialties: ["Cardiology", "Pediatrics", "Oncology", "Orthopedics", "Nephrology"],
    totalBeds: 800,
    availableBeds: 105,
    totalICUBeds: 75,
    availableICUBeds: 16,
    emergencyAvailable: true,
    ambulanceAvailable: true,
    rating: 4.6,
    latitude: 12.8167,
    longitude: 77.6974,
  },
];

async function main() {
  await ensureHospitalsSchema();
  console.log("✓ Hospitals schema ready");

  await db.delete(hospitalsTable);
  console.log("Cleared existing hospitals");

  const inserted = await db.insert(hospitalsTable).values(hospitals).returning();
  console.log(`✓ Seeded ${inserted.length} hospitals across India`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
